version: 2

linters:
  presets:
    - comment
    - bugs
    - performance
    - unused
    - test
    - sql
    - style

  enable:
    - wsl_v5

  disable:
    - godox
    - tagalign
    - exhaustruct
    - depguard
    - wrapcheck
    - gochecknoinits
    - varnamelen
    - funlen
    - ireturn
    - mnd
    - interfacebloat
    - gochecknoglobals
    - err113
    - lll
    - nilnil
    - containedctx
    - dupword # for swagger docs

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

  exclusions:
    paths:
      - ".*_test\\.go$"
    rules:
      - text: "the type name `ErrorResponse` should conform to the `XxxError` format"
        linters:
          - revive
          - stylecheck
      - path: openid4vci/
        linters:
          - tagliatelle # for OpenID specification json naming

formatters:
  presets:
    - format

  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(git.zzdats.lv/edim/api-wallet)
        - default

  exclusions:
    paths:
      - ".*_test\\.go$"