sonar.projectKey=unknovs_status-list-go
sonar.organization=unknovs
sonar.projectName=status-list-go

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/*.pb.go

sonar.go.coverage.reportPaths=coverage.out
sonar.tests=.
sonar.test.inclusions=**/*_test.go